name: id3_android_license
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: eu.id3.id3_android_license
        pluginClass: Id3AndroidLicensePlugin