name: benchmark_sample
description: id3 Face SDK benchmark sample.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  async: ^2.8.2
  flutter:
    sdk: flutter
  id3_android_license:
    path: ../id3_android_license
  id3_face:
    path: ../../sdk/dart/id3_face
  path_provider: ^2.0.8
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/